name: Pulumi Destroy OIDC

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  pulumi-destroy:
    name: pulumi-destroy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./ppinfra
        run: npm install

      - name: Authenticate with Pulumi
        uses: pulumi/auth-actions@v1
        with:
          organization: valooran-org
          requested-token-type: urn:pulumi:token-type:access_token:organization

      - uses: pulumi/actions@v5
        with:
          command: destroy
          stack-name: valooran-org/myworkshop/dev
          work-dir: ./ppinfra
